WebApplication1/Controllers/NurseEventController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.DAL;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    [Authorize]
    public class NurseEventController : Controller
    {
        private NurseEventContext db;

        public NurseEventController()
        {
            db = new NurseEventContext();
            db.Database.Log = s => System.Diagnostics.Trace.WriteLine(s);
        }

        public ActionResult Index()
        {
            return Index("", "", true, true);
        }

        [ActionName("Index1")]
        public ActionResult Index(string searchfromdate = "", string searchtodate = "", bool searchyettohandle = true, bool searchandled = true)
        {
            var checkExpression = PredicateBuilder.True<NurseEvent>();

            DateTime fromtime;
            if (DateTime.TryParse(searchfromdate + " 00:00:00", out fromtime))
            {
                if ((fromtime > DateTime.Now.AddDays(-1)) || (fromtime < DateTime.Now.AddYears(-2)))
                {
                    fromtime = Convert.ToDateTime(DateTime.Now.AddYears(-1).ToString("yyyy-MM-dd") + " 00:00:00");
                }
            }
            else
            {
                fromtime = Convert.ToDateTime(DateTime.Now.AddYears(-1).ToString("yyyy-MM-dd") + " 00:00:00");
            }
            checkExpression = checkExpression.And(s => s.event_happen_time > fromtime);

            DateTime totime;
            if (DateTime.TryParse(searchtodate + " 00:00:00", out totime))
            {
                if ((totime > DateTime.Now.AddDays(-1)) || (totime < DateTime.Now.AddYears(-2)))
                {
                    totime = Convert.ToDateTime(DateTime.Now.ToString("yyyy-MM-dd") + " 00:00:00");
                }
            }
            else
            {
                totime = Convert.ToDateTime(DateTime.Now.ToString("yyyy-MM-dd") + " 00:00:00");
            }
            checkExpression = checkExpression.And(s => s.event_happen_time < totime);
            

            if (User.IsInRole("领导组"))
            {

            }
            else if (User.IsInRole("护士组") || User.IsInRole("护士长组"))
            {
                string dept_name = User.Identity.Name.Split(new char[] { ',' })[2].TrimEnd("护理站".ToCharArray());
                checkExpression = checkExpression.And(s => s.dept_name == dept_name);
            }

            if (searchandled)
            {
                checkExpression = checkExpression.And(s => s.handled_by_headnurse == "dept_name");
            }
            if (searchyettohandle)
            {
                checkExpression = checkExpression.And(s => s.handled_by_headnurse == "dept_name");
            }
            //var tmp = db.NurseEvents.Where(checkExpression);
            //string sql = ((System.Data.Entity.Core.Objects.ObjectQuery)tmp).ToTraceString();
            return View("Index",db.NurseEvents.Where(checkExpression).ToList());

        }

        // GET: NurseEvent/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NurseEvent nurseEvent = db.NurseEvents.Find(id);
            if (nurseEvent == null)
            {
                return HttpNotFound();
            }
            return View(nurseEvent);
        }

        // GET:
        public ActionResult PartialDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NurseEvent nurseEvent = db.NurseEvents.Find(id);
            if (nurseEvent == null)
            {
                return HttpNotFound();
            }
            return PartialView("_PartialDetails", nurseEvent);
        }

        // GET: NurseEvent/Create
        public ActionResult Create()
        {
            NurseEvent nurseEvent = new NurseEvent {event_happen_time=DateTime.Now, reporter_id = User.Identity.Name.Split(new char[] { ',' })[0], reporter_name = User.Identity.Name.Split(new char[] { ',' })[1] };
            return View(nurseEvent);
        }

        // POST: NurseEvent/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,patient_name,dept_name,bed_no,patient_age,patient_sex,charge_type,diagnosis,inp_no,admission_date,event_happen_time,event_info,event_level,event_service,event_name,event_fact,event_relevant_factor,event_patient_status,event_harm,event_harm_grade,event_location,event_concerned_staff1,event_concerned_staff2,event_concerned_staff3,event_treatment,event_treatment_after,reporter_name,reporter_id,handled_by_headnurse,handled_by_leader")] NurseEvent nurseEvent)
        {
            if (ModelState.IsValid)
            {
                db.NurseEvents.Add(nurseEvent);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(nurseEvent);
        }

        // GET: NurseEvent/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NurseEvent nurseEvent = db.NurseEvents.Find(id);
            if (nurseEvent == null)
            {
                return HttpNotFound();
            }
            return View(nurseEvent);
        }

        // POST: NurseEvent/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,patient_name,dept_name,bed_no,patient_age,patient_sex,charge_type,diagnosis,inp_no,admission_date,event_happen_time,event_info,event_level,event_service,event_name,event_fact,event_relevant_factor,event_patient_status,event_harm,event_harm_grade,event_location,event_concerned_staff1,event_concerned_staff2,event_concerned_staff3,event_treatment,event_treatment_after,reporter_name,reporter_id,handled_by_headnurse,handled_by_leader")] NurseEvent nurseEvent)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nurseEvent).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(nurseEvent);
        }

        // GET: NurseEvent/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NurseEvent nurseEvent = db.NurseEvents.Find(id);
            if (nurseEvent == null)
            {
                return HttpNotFound();
            }
            return View(nurseEvent);
        }

        // POST: NurseEvent/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            NurseEvent nurseEvent = db.NurseEvents.Find(id);
            db.NurseEvents.Remove(nurseEvent);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 监利县人民医院</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.Label("监利县人民医院", new { @class = "navbar-brand" })*@
                @Html.ActionLink("监利县人民医院", "Index", "NurseEvent", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("报告", "Create", "NurseEvent")</li>
                    <li>@Html.ActionLink("查询", "Index", "NurseEvent")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 监利县人民医院</p>
        </footer>
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>

WebApplication1/Views/Shared/_PartialDetails.cshtml
@model WebApplication1.Models.NurseEvent

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-body">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.patient_name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.patient_name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.dept_name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.dept_name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.bed_no)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.bed_no)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.patient_age)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.patient_age)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.patient_sex)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.patient_sex)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.charge_type)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.charge_type)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.diagnosis)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.diagnosis)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.inp_no)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.inp_no)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.admission_date)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.admission_date)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.event_happen_time)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.event_happen_time)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.event_info)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.event_info)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.event_level)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.event_level)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.event_service)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.event_service)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.event_name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.event_name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.event_fact)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.event_fact)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.event_relevant_factor)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.event_relevant_factor)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.event_patient_status)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.event_patient_status)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.event_harm)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.event_harm)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.event_harm_grade)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.event_harm_grade)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.event_location)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.event_location)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.event_concerned_staff1)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.event_concerned_staff1)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.event_concerned_staff2)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.event_concerned_staff2)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.event_concerned_staff3)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.event_concerned_staff3)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.event_treatment)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.event_treatment)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.event_treatment_after)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.event_treatment_after)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.reporter_name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.reporter_name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.reporter_id)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.reporter_id)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.handled_by_headnurse)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.handled_by_headnurse)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.handled_by_leader)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.handled_by_leader)
                </dd>

            </dl>
        </div>
    </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->