WebApplication1/Controllers/AuthenticationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Security;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class AuthenticationController : Controller
    {
        // GET: Authentication
        [AllowAnonymous]
        public ActionResult Login()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult Login(string Username, string Password)
        {
            if (!string.IsNullOrEmpty(Username) && !string.IsNullOrEmpty(Password))
            {
                string dept_name; string name; string password; string role;
                DataService.get_staff(Username,out dept_name,out name,out password,out role);
                if(Password == password)
                {
                    FormsAuthenticationTicket ticket = new FormsAuthenticationTicket(1,
                                                                                     Username + "," + name + "," + dept_name,
                                                                                     DateTime.Now,
                                                                                     DateTime.Now.AddMinutes(15),
                                                                                     false,
                                                                                     role);
                    string encryptedTicket = FormsAuthentication.Encrypt(ticket);
                    HttpCookie authCookie = new System.Web.HttpCookie(FormsAuthentication.FormsCookieName, encryptedTicket);
                    authCookie.HttpOnly = true;
                    System.Web.HttpContext.Current.Response.Cookies.Add(authCookie);
                    return RedirectToAction("Index", "NurseEvent");
                }
            }
            ModelState.AddModelError("", "无效的登录尝试。");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LogOff()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "NurseEvent");
        }

    }
}

WebApplication1/Views/Authentication/Login.cshtml
@{
    ViewBag.Title = "登录";
}

<h2>登录</h2>

<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            @using (Html.BeginForm("Login", "Authentication", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    <div class="col-md-10">
                        @Html.TextBox("UserName", "", new { placeholder = "请输入用户名" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-10">
                        @Html.Password("Password", "", new { placeholder = "请输入密码" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="登录" class="btn btn-default" />
                    </div>
                </div>
            }
        </section>
    </div>

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}